# Generated by Django 2.2.3 on 2019-08-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtask',
            name='since_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
