# Generated by Django 2.2.4 on 2019-08-25 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_searchtask_since_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biterm',
            fields=[
                ('biterm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('biterm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hashtags.Biterm')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hashtags.Hashtag')),
            ],
            options={
                'unique_together': {('biterm', 'hashtag')},
            },
        ),
        migrations.CreateModel(
            name='HashtagTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('since_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('waiting', '待ち'), ('processing', '処理中'), ('finished', '完了')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hashtag', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hashtags.Hashtag')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('char_string', models.CharField(db_index=True, max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchTask',
        ),
        migrations.AddField(
            model_name='biterm',
            name='word_i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word_i', to='hashtags.Word'),
        ),
        migrations.AddField(
            model_name='biterm',
            name='word_j',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word_j', to='hashtags.Word'),
        ),
        migrations.AlterUniqueTogether(
            name='biterm',
            unique_together={('word_i', 'word_j')},
        ),
    ]
