# Generated by Django 2.2.4 on 2019-08-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0003_auto_20190825_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biterm',
            unique_together={('word_i', 'word_j'), ('word_j', 'word_i')},
        ),
        migrations.AlterUniqueTogether(
            name='cooccurrence',
            unique_together=set(),
        ),
    ]
