# Generated by Django 2.2.4 on 2019-08-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0004_auto_20190826_1555'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biterm',
            unique_together={('word_i', 'word_j')},
        ),
    ]
