# Generated by Django 2.2.4 on 2019-08-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0006_auto_20190826_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biterm',
            name='biterm_id',
            field=models.CharField(editable=False, max_length=72, primary_key=True, serialize=False),
        ),
    ]
